;/*FB_PKG_DELIM*/

__d("CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities$normalization.graphql",["CometTextWithEntitiesRelay_textWithEntities$normalization.graphql"],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities$normalization",selections:[{args:null,fragment:b("CometTextWithEntitiesRelay_textWithEntities$normalization.graphql"),kind:"FragmentSpread"}]};e.exports=a}),null);
__d("CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities",selections:[{args:null,kind:"FragmentSpread",name:"CometTextWithEntitiesRelay_textWithEntities"}],type:"TextWithEntities",abstractKey:null};e.exports=a}),null);
__d("CometMediaViewerDescriptionSectionTextWithEntities.react",["CometEmojiTransform","CometEmoticonTransform","CometHovercardEntityRenderer","CometLineBreakTransform","CometLinkedEntityRenderer","CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities.graphql","CometRelay","CometShortenedExternalUrlEntityRenderer","CometTextWithEntitiesRelay.react","CometTrackingNodeRenderer","PageWhatsAppNumberCometRenderer","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react"),j={"*":[c("CometLinkedEntityRenderer"),c("CometTrackingNodeRenderer")],Event:[c("CometHovercardEntityRenderer")],ExternalUrl:[c("CometShortenedExternalUrlEntityRenderer")],Group:[c("CometHovercardEntityRenderer")],Page:[c("CometHovercardEntityRenderer")],PageWhatsAppNumber:[c("PageWhatsAppNumberCometRenderer")],User:[c("CometHovercardEntityRenderer")]},k=[c("CometEmoticonTransform")(),c("CometEmojiTransform")(),c("CometLineBreakTransform")];function a(a){a=a.textWithEntities;a=d("CometRelay").useFragment(h!==void 0?h:h=b("CometMediaViewerDescriptionSectionTextWithEntities_textWithEntities.graphql"),a);return a==null?null:i.jsx(c("CometTextWithEntitiesRelay.react"),{renderers:j,textWithEntities:a,transforms:k,truncationStyle:"see-more-and-less"})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometMarketplaceSellerAnnouncementCenterContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5156325217748820"}),null);
__d("CometMarketplaceYouPromotionsContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5538494296181546"}),null);
__d("GroupCometReschedulePostDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4477410095698112"}),null);
__d("MarketplaceCometSetUpShippingLandingExperienceDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5699885520113934"}),null);
__d("MarketplaceYouInsightsContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5999689120151896"}),null);
__d("PageCometLaunchpointInvitesRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7224925170868877"}),null);
__d("PagesCometAPLaunchpointPagesListQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6508001822545223"}),null);
__d("PagesCometPagesLikedRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6397133833674455"}),null);