;/*FB_PKG_DELIM*/

__d("useInnerMostTrackingCode",["CometTrackingCodeContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=h(c("CometTrackingCodeContext")),b={click_tracking_linkshim_cb:[],encrypted_click_tracking:[],encrypted_tracking:[]};for(var d in a){var e=a[d],f=e.length;b[d]=f>0?[e[f-1]]:[]}return b}g["default"]=a}),98);
__d("formatDurationSeconds",["fbt","padNumber"],(function(a,b,c,d,e,f,g,h){function a(a){var b=Math.floor(a/3600),d=Math.floor(a/60%60);a=Math.floor(a%60);if(b)return h._("__JHASH__FQybzYZtMhO__JHASH__",[h._param("hours",b),h._param("minutes",c("padNumber")(d,2)),h._param("seconds",c("padNumber")(a,2))]);else return h._("__JHASH__dB1Hg5AxmjF__JHASH__",[h._param("minutes",d),h._param("seconds",c("padNumber")(a,2))])}g["default"]=a}),98);
__d("VideoPlayerTimeIndicator.react",["TetraText.react","formatDurationSeconds","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){var b=a.shouldCenterSelf;a=a.timestampSec;var d=b===!0?"var(--always-black)":"var(--always-dark-overlay)";d=h.jsx("div",{className:"x18l40ae x1lcm9me x1yr5g0i xrt01vj x10y3i5r x1wa3icf x123j3cw x1mpkggp xs9asl8 x1t2a60a x10l6tqk xuxw1ft",style:{backgroundColor:d},children:h.jsx(c("TetraText.react"),{color:"primaryOnMedia",type:"body4",children:c("formatDurationSeconds")(Math.round(a))})});return b===!0?h.jsx("div",{className:"x78zum5 xl56j7k x1n2onr6",children:d}):d}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("useIsVideoHomePlayerOriginFromTracePolicy",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=["comet.watch.catalog","comet.watch.explore","comet.watch.feed","comet.watch.injection","comet.watch.latest","comet.watch.notifications","comet.watch.playlist","comet.watch.saved","comet.watch.search","comet.watch.sports","comet.watch.live.injection","comet.watch.live","comet.watch.music","comet.watch.lancelet"];return b.includes(a)}f["default"]=a}),66);
__d("useNavigateToTahoePassthroughProps",["CometProductTagFunnelIDContext","CometTrackingCodeContext","CometTrackingNodesContext","CometWarningScreenContext","VideoPlayerHooks","getAggregatedStoryTrackingNodeIndex","react","useIsVideoHomePlayerOriginFromTracePolicy","usePlayerOriginRouteTracePolicy","useVideoPlayerPortalingPassthroughProps"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=c("useVideoPlayerPortalingPassthroughProps")(),b=h(c("CometTrackingCodeContext")),e=h(c("CometTrackingNodesContext")),f=h(c("CometProductTagFunnelIDContext")),g=d("CometWarningScreenContext").useIsOverlayShown(),i=d("CometWarningScreenContext").useHasOverlay();e=c("getAggregatedStoryTrackingNodeIndex")(e);var j=d("VideoPlayerHooks").useVideoPlayerInitialTracePolicy(),k=c("usePlayerOriginRouteTracePolicy")(),l=c("useIsVideoHomePlayerOriginFromTracePolicy")(k);return babelHelpers["extends"]({bypassAutoplaySettings:!0},a,{index:e,initialTracePolicy:(a=j)!=null?a:k,origOverlayShown:g,overlayExists:i,productTagFunnelID:f,trackingCode:b},l?{caller:"CHANNEL_VIEW_FROM_VIDEO_HOME"}:{})}g["default"]=a}),98);
__d("VideoPlayerLoggingSuboriginContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(null);g["default"]=b}),98);
__d("VideoHomeTypedLiteLogger",["generateLiteTypedLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=b("generateLiteTypedLogger")("logger:VideoHomeLoggerConfig")}),null);
__d("CometVideoHomePositionInUnitContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(0);g["default"]=b}),98);
__d("CometVideoHomeSectionPositionContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(null);g["default"]=b}),98);
__d("VideoHomeLoggingReactionVideoChannelTypeContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(null);g["default"]=b}),98);
__d("VideoHomeLoggingUpstreamPlayerSourceContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(null);g["default"]=b}),98);
__d("CometWatchAndScrollControlNUXContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b={isVideoPlayerWatchAndScrollControlNUXVisible:!1,setIsVideoPlayerWatchAndScrollControlNUXVisible:null};c=a.createContext(b);g["default"]=c}),98);
__d("VideoPlayerCometWatchInjectionControl.react",["fbt","ix","VideoPlayerControlIcon.react","fbicon","react","useCometRouterState","useVideoPlayerPortalingPassthroughProps"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j=d("react");function a(a){var b=a.isARLTW,e=a.onPress,f=a.routeTracePolicy,g=a.subOrigin;a=a.videoWatchUrl;var k=c("useVideoPlayerPortalingPassthroughProps")();k=k.portableVideoID;var l=c("useCometRouterState")();l=l==null?void 0:l.main.route.tabKey;l=l!=="watch"?h._("__JHASH__jqpm3epcsS4__JHASH__"):h._("__JHASH__NFrEQFQldyW__JHASH__");return j.jsx(c("VideoPlayerControlIcon.react"),{icon:d("fbicon")._(i("517763"),20),label:l,linkProps:{passthroughProps:{isARLTW:b,portableVideoID:k,portalingRouteTracePolicy:f,portalingSubOrigin:g,unmute:!0},url:a},onPress:e,tooltip:l})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);