;/*FB_PKG_DELIM*/

__d("CometUFICommentEditHistoryDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6195704323885630"}),null);
__d("CometUFICommentEditHistoryDialogQuery$Parameters",["CometUFICommentEditHistoryDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometUFICommentEditHistoryDialogQuery_facebookRelayOperation"),metadata:{},name:"CometUFICommentEditHistoryDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometUFIEditHistoryCommentActionLink_comment.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometUFIEditHistoryCommentActionLink_comment",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],type:"Comment",abstractKey:null};e.exports=a}),null);
__d("CometUFICommentEditHistoryActionLink_commentActionLink$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometUFICommentEditHistoryActionLink_commentActionLink$normalization",selections:[{alias:null,args:null,concreteType:"Comment",kind:"LinkedField",name:"comment",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}]};e.exports=a}),null);
__d("CometUFICommentEditHistoryActionLink_commentActionLink.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometUFICommentEditHistoryActionLink_commentActionLink",selections:[{alias:null,args:null,concreteType:"Comment",kind:"LinkedField",name:"comment",plural:!1,selections:[{args:null,kind:"FragmentSpread",name:"CometUFIEditHistoryCommentActionLink_comment"}],storageKey:null}],type:"XFBCommentEditHistoryActionLink",abstractKey:null};e.exports=a}),null);
__d("CometUFICommentEditHistoryDialog.entrypoint",["CometUFICommentEditHistoryDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.commentID;return{queries:{root:{options:{fetchPolicy:"network-only"},parameters:b("CometUFICommentEditHistoryDialogQuery$Parameters"),variables:{commentID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometUFICommentEditHistoryDialog.react").__setRef("CometUFICommentEditHistoryDialog.entrypoint")};g["default"]=a}),98);
__d("CometUFIEditHistoryCommentActionLink.react",["fbt","CometLink.react","CometRelay","CometTooltip.react","CometUFICommentEditHistoryDialog.entrypoint","CometUFIEditHistoryCommentActionLink_comment.graphql","react","recoverableViolation","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=d("react");e=d("react");var k=e.useCallback,l=e.useRef,m={link:{color:"xi81zsa",$$css:!0}};function a(a){var e=d("CometRelay").useFragment(i!==void 0?i:i=b("CometUFIEditHistoryCommentActionLink_comment.graphql"),a.comment),f=e.id;e=l(null);var g=c("useCometEntryPointDialog")(c("CometUFICommentEditHistoryDialog.entrypoint"),f!=null?{commentID:f}:null,"button"),n=g[0],o=g[1],p=g[2];g=g[3];var q=k(function(){if(f==null){c("recoverableViolation")("Cannot open dialog for comment without an ID","ufi2");return}n({})},[f,n]);return j.jsx(c("CometTooltip.react"),{align:a==null?void 0:a.tooltipAlignment,tooltip:h._("__JHASH___IlNPcoO45M__JHASH__"),children:j.jsx(c("CometLink.react"),{onClick:q,onHoverEnd:p,onHoverStart:o,onPressStart:g,ref:e,testid:void 0,xstyle:m.link,children:h._("__JHASH__ZM2WATDKeTW__JHASH__")})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometUFICommentEditHistoryActionLink.react",["CometRelay","CometUFICommentActionLinksListItem.react","CometUFICommentEditHistoryActionLink_commentActionLink.graphql","CometUFIEditHistoryCommentActionLink.react","FBLogger","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");function a(a){a=a.commentActionLink;a=d("CometRelay").useFragment(h!==void 0?h:h=b("CometUFICommentEditHistoryActionLink_commentActionLink.graphql"),a);a=a.comment;if(a==null){c("FBLogger")("ufi2").mustfix("CometUFICommentEditHistoryActionLink: Can't render edit history action link without a valid comment");return null}return i.jsx(c("CometUFICommentActionLinksListItem.react"),{children:i.jsx(c("CometUFIEditHistoryCommentActionLink.react"),{comment:a})},"editHistoryLink")}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);